### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by beatrizgerogiannis** [plinioleitao/bd-2024-2-bcc#12]
Meu registro: 202200495
Meu git: https://github.com/beatrizgerogiannis
Expectativas: Espero adquirir uma compreensão sólida dos conceitos fundamentais de bancos de dados, como modelagem e normalização, e desenvolver habilidades práticas em SQL e ferramentas de gerenciamento. Desejo aprender a projetar e implementar bancos de dados eficientes, gerenciar transações, e explorar tecnologias avançadas como NoSQL e Big Data. Além disso, gostaria de entender práticas de segurança e backup, otimização de desempenho, e a integração de bancos de dados com aplicações, participando de projetos práticos e colaborativos.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários. Por favor, suas expectativas mencionam conteúdos que não compõem a ementa da disciplina, precisamos nos concentrar nos da própria ementa.
