### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by Igor-Guedes** [plinioleitao/bd-2024-2-bcc#13]
Meu registro acadêmico: 202103734
Minha no GitHub: https://github.com/Igor-Guedes
Minhas expectativas com respeito à disciplina: Aprender a manipular, programar e projetar Bancos de Dados, aprender a trabalhar com SQL, e os métodos de organização e projeção de banco de dados.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
