### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by code-pedrolsl** [plinioleitao/bd-2024-2-bcc#15]
## Meu registro acadêmico: 

- 202200550

## Minha no Github: https:

- [https://github.com/code-pedrolsl](url)

## Minhas expectativas com respeito à disciplina:

- Espero aprender e desenvolver conhecimentos sólidos a respeito da disciplina, além de obter um bom desempenho nas atividades realizadas. Também tenho como expectativa conseguir criar e participar de projetos com banco de dados.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
