### ISSUE TITLE
[Dúvida] Tópico <01>

### ISSUE THREAD

**Issue by AnaCarolynePds** [plinioleitao/bd-2024-2-bcc#16]
Meu registro:  202200490
Meu git: https://github.com/AnaCarolynePds
Expectativas: Minhas expectativas para esta matéria são aprender profundamente o conteúdo apresentado e desenvolver habilidades práticas que me permitam aplicar esse conhecimento de forma eficaz no mercado de trabalho. Espero que o curso me prepare para enfrentar desafios reais e me ajude a integrar conceitos teóricos com práticas profissionais

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
