### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by analuisabc** [plinioleitao/bd-2024-2-bcc#17]
**Meu registro acadêmico:** 202200491

**Minha no GitHub:**  https://github.com/analuisabc

**Minhas expectativas com respeito à disciplina:** Como aluna desta disciplina, espero adquirir uma compreensão abrangente dos conceitos fundamentais e das práticas essenciais relacionadas aos bancos de dados. Espero realizar projetos com outros alunos, aplicando o conhecimento obtido.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
