### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by JulioCesarAraujo** [plinioleitao/bd-2024-2-bcc#18]
Meu registro acadêmico: 202204769
Minha no GitHub: https://github.com/JulioCesarAraujo
Minhas expectativas com respeito à disciplina: Desenvolver conhecimento sobre banco de dados e SQL, além de dominar outros conteúdos relacionados a disciplina. Desenvolver um bom projeto da disciplina para ter maior certeza sobre o conhecimento absorvido.  E claro que tenho expectativa de passar na disciplina.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
