### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by Giodzz** [plinioleitao/bd-2024-2-bcc#19]
## Meu registro acadêmico
- 202200513

## Minha no GitHub
- https://github.com/Giodzz

## Minhas expectativas com respeito à disciplina
- compreender conceitos (iniciais) relacionados a área de Banco de Dados;
- aprender a utilizar e projetar um Banco de Dados; e
- como aplicar os conhecimentos adquiridos em projetos de Softwares reais

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
