### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by felipeLeao18** [plinioleitao/bd-2024-2-bcc#2]
## Meu registro acadêmico 
 - 202000177
 ## Minha conta no Github
 - https://github.com/felipeLeao18
 
 ## Minhas expectativas com respeito à disciplina:
  - Aprofundamento teórico
  - Mesclar o conhecimento teórico aprofundado com o prático
  - Melhorar a tomada de decisão em projetos reais

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
