### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by vitor-rodovalho** [plinioleitao/bd-2024-2-bcc#20]
Matrícula: 202301490
Conta do GitHub: https://github.com/vitor-rodovalho
Minhas expectativas para com a disciplina: espero aprender a lidar melhor com dados, e manusear, estruturar, organizar e realizar quaisquer outras operações necessárias com bancos de dados, para aplicar principalmente em análise de dados e aprendizado de máquina. Além disso, busco expandir o horizonte de conhecimentos até onde me for possível, então espero descobrir coisas novas e me divertir no percurso, além de construir uma base sólida de entendimento da lógica dos bancos de dados

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
