### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by JoaoPSantos0** [plinioleitao/bd-2024-2-bcc#22]
# Nome e matrícula

João Pedro Santos Morais/ 202306975
# Conta github

 https://github.com/JoaoPSantos0

# Expectativas

- Compreender os principais conceitos de bancos de dados;
-  Melhorar a capacidade de abstração física do conceito de dados, modelos e etc;
-  Adquirir a capacidade técnica de elaboração e manipulação de banco de dados;

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
