### ISSUE TITLE
Tópico 1

### ISSUE THREAD

**Issue by stdMurilloMelo** [plinioleitao/bd-2024-2-bcc#23]
- Meu registro acadêmico: 202300074
- Minha conta no GitHub: [github.com/stdMurilloMelo](https://github.com/stdMurilloMelo)
- Espero aprender a modelar, criar e otimizar bancos de dados, além de dominar o uso de SQL e técnicas para garantir a integridade e segurança dos dados.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
