### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by joao-vitorCC** [plinioleitao/bd-2024-2-bcc#24]
**Meu registro acadêmico**: 201702762
**Minha no GitHub:** https://github.com/joao-vitorCC
**Minhas expectativas com respeito à disciplina:**  Minhas expectativas nessa disciplina é obter um grande desenvolvimento na criação de bancos de dados e nas consultas ao banco. Eu gostaria de aprender os conceitos de normalização e entender melhor álgebra relacional.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
