### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by pedroantonio-18** [plinioleitao/bd-2024-2-bcc#29]
Meu registro acadêmico: 202307091
Minha no GitHub: https://github.com/pedroantonio-18
Minhas expectativas com respeito à disciplina: Espero que através da disciplina, eu adiquira uma base sólida para compreender, criar e manipular bancos de dados de maneira eficaz além de também aprender a trabalhar com a linguagem de programação especificada para a matéria (SQL)

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
