### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by lauanemateus** [plinioleitao/bd-2024-2-bcc#32]
* Registro acadêmico: 202103747
* Conta no GitHub: https://github.com/lauanemateus
* Expectativas a respeito da disciplina: eu não tenho nenhum conhecimento prévio de banco de dados, logo espero ter um embasamento inicial para construir, compreender e manipular um banco de dados. Além disso, eu gostaria de ter um aprendizado inicial de SQL.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
