### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by lucasmiguelin** [plinioleitao/bd-2024-2-bcc#34]
Meu registro acadêmico: 202204036
Minha no GitHub: https://github.com/lucasmiguelin
Minhas expectativas com respeito à disciplina: Pretendo introduzir e concretizar os conhecimentos de bancos de dados na minha formação acadêmica. Se possível, desenvolver conhecimentos suficientes para implementar um banco de dados na pratica.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
