### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by giorrdanna** [plinioleitao/bd-2024-2-bcc#35]
Meu registro acadêmico: 202008055
Minha no GitHub: https://github.com/giorrdanna
Minhas expectativas com respeito à disciplina: Espero poder adquirir conhecimento na área de fundamentos de banco de dados, bem como banco de dados relacionais e não relacionais, desenvolver base teórica e prática na disciplina e que ao final do semestre esteja dominando SQL.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
