### ISSUE TITLE
Tópico 01 

### ISSUE THREAD

**Issue by AndreFilho0** [plinioleitao/bd-2024-2-bcc#36]
Meu registro acadêmico: 202406913
Minha conta no GitHub: https://github.com/AndreFilho0
Minhas expectativas com respeito à disciplina: Espero poder adquirir o conhecimento que está na ementa : Conceitos básicos de Banco de Dados. Modelo relacional. Linguagens para Banco de Dados: álgebra
relacional, cálculo relacional e SQL. Modelo Entidade-Relacionamento e extensões. Mapeamento
ER-relacional. Normalização.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
