### ISSUE TITLE
Tópico 1

### ISSUE THREAD

**Issue by PedroLSeabra** [plinioleitao/bd-2024-2-bcc#38]
Meu registro acadêmico: 202200553
Minha no GitHub:  https://github.com/PedroLSeabra
Minhas expectativas com respeito à disciplina: Espero adquirir conhecimento sólido dos conceitos fundamentais como modelagem de dados e SQL, da mesma forma que espero desenvolver habilidades práticas na implementação e gerenciamento de bancos de dados.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
