### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by Ramos-Santos** [plinioleitao/bd-2024-2-bcc#39]
Meu registro acadêmico: 202301445
Minha no Github: https://github.com/Ramos-Santos
minhas expectativas com respeito a disciplina: obter uma boa base pratica e teórica sobre banco de dados e  ao final do semestre estar proficiente no uso da linguagem SQL.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
