### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by ZKPGDNHO** [plinioleitao/bd-2024-2-bcc#5]
Meu registro acadêmico: 202301481

Minha conta no GitHub: https://github.com/ZKPGDNHO

Minhas expectativas com respeito à disciplina: Espero conseguir aprender bastante sobre a matéria de Banco de Dados e como funciona um banco de dados, e de que forma ele é executado

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
