### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by esqzerolol** [plinioleitao/bd-2024-2-bcc#6]
Registro Acadêmico: 202205559
Conta GitHub: https://github.com/esqzerolol/
Minhas Expectativas: Espero sair da disciplina com conhecimentos básicos de Banco de Dados, principalmente para que eu consiga criar projetos próprios, integrando dados de aplicativos de minha criação. Assim como também espero conhecer parte da teoria por trás dos Bancos de Dados, pois a parte que mais gosto da Computação é a Teoria.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários.
