### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by acsamendes** [plinioleitao/bd-2024-2-bcc#8]
Registro acadêmico: 202301418
Conta do GitHub: https://github.com/acsamendes
Expectativas: É uma disciplina da qual tive contato no ensino médio e gostei bastante. Espero me sair bem e me ambientar na área de conhecimento e possíveis ramos de pesquisa.

**Comment by plinioleitao** [comment]
Obrigado pela resposta e comentários. É pertinente você compartilhar sobre o seu contato com a disciplina durante o ensino médio.
